import type { VoyageRecord } from "./types";

export const voyages: VoyageRecord[] = [
  {
    id: "demo",
    vessel: "MV Cedar Bay",
    owner: "Northshore Bulk Pte. Ltd.",
    charterer: "Golden Delta Foods",
    broker: "Harborline Brokers",
    cargo: "4,800 MT corn",
    route: "Novorise › Southbay",
    freight: "USD 168,000",
    paymentTerm: "Within 3 banking days after B/L signing",
    status: "Loading",
    stage: "LOADING",
    nextTrigger: "B/L signing",
    nextDeadline: "ETA 5 days notice",
    riskLevel: "Medium",
    health: {
      label: "Medium risk",
      tone: "medium",
      reasons: [
        "NOR timing uncertain",
        "B/L not yet uploaded",
        "SOF still missing",
      ],
    },
    parserSummary: [
      { label: "Freight term", value: "3 banking days after B/L signing" },
      { label: "Demurrage", value: "USD 6,000 PD" },
      { label: "Claim deadline", value: "15 business days after discharge" },
      { label: "Laytime exclusion", value: "Weather and non-ready holds period excluded" },
    ],
    flags: [
      { title: "Freight deadline approaching", severity: "medium" },
      { title: "Missing SOF", severity: "high" },
      { title: "NOR before laycan risk", severity: "medium" },
    ],
    summary: [
      ["Owner", "Northshore Bulk Pte. Ltd."],
      ["Charterer", "Golden Delta Foods"],
      ["Broker", "Harborline Brokers"],
      ["Cargo", "4,800 MT corn"],
      ["Loadport", "Novorise"],
      ["Disport", "Southbay"],
      ["Freight", "4,800 × 35 = USD 168,000"],
      ["Payment", "3 banking days after B/L signing"],
    ],
    ownerTasks: [
      {
        title: "ETA 5 days notice",
        owner: "Owner",
        detail: "Reminder draft prepared for master and ops.",
        status: "pending",
        actions: [
          { label: "Send ETA Notice", tone: "primary" },
          { label: "Edit Reminder" },
        ],
      },
      {
        title: "NOR template ready",
        owner: "Owner",
        detail: "Template checked against laycan and tender location wording.",
        status: "ready",
        actions: [
          { label: "Upload NOR", tone: "primary" },
          { label: "Mark NOR Tendered" },
        ],
      },
      {
        title: "Holds inspection follow-up",
        owner: "Owner",
        detail: "Awaiting surveyor result and photo upload.",
        status: "active",
        actions: [
          { label: "Upload Hold Photos", tone: "primary" },
          { label: "Upload Survey Report" },
        ],
      },
      {
        title: "Demurrage claim pack window",
        owner: "Owner",
        detail: "15 business day filing clock will activate after discharge.",
        status: "pending",
        actions: [{ label: "Open Claim Builder", tone: "primary" }],
      },
    ],
    chartererTasks: [
      {
        title: "Agent nomination",
        owner: "Charterer",
        detail: "Loadport agent nomination still missing.",
        status: "pending",
        actions: [
          { label: "Upload Nomination", tone: "primary" },
          { label: "Notify Agent" },
        ],
      },
      {
        title: "PDA entry",
        owner: "Charterer",
        detail: "Expected PDA deduction must be uploaded before freight due.",
        status: "pending",
        actions: [{ label: "Upload PDA", tone: "primary" }],
      },
      {
        title: "Freight instruction prep",
        owner: "Charterer",
        detail: "Remittance path drafted, awaiting B/L signing trigger.",
        status: "ready",
        actions: [
          { label: "Generate Freight Reminder", tone: "primary" },
          { label: "Upload Payment Proof" },
        ],
      },
      {
        title: "Surveyor nomination",
        owner: "Charterer",
        detail: "Cargo and hold survey contacts not yet confirmed.",
        status: "active",
        actions: [{ label: "Add Surveyor", tone: "primary" }],
      },
    ],
    triggers: [
      "Arrival at Outer Roads",
      "NOR tender",
      "Loading complete",
      "B/L signed",
      "Freight due",
      "Discharge complete",
      "Demurrage claim deadline",
    ],
    documents: [
      "Recap / CP extract",
      "Arrival report",
      "NOR",
      "Survey report / hold photos",
      "B/L",
      "SOF",
      "PDA / Final DA invoice",
      "SWIFT payment proof",
    ],
    riskNotes: [
      "NOR must not be tendered before laycan or outside allowed place wording.",
      "Failed hold inspection may suspend laytime counting and require fresh NOR.",
      "Freight amount may reduce by PDA if recap wording confirms deduction.",
      "Demurrage claim pack must include signed SOF and laytime sheet within 15 business days.",
    ],
    timeline: [
      {
        title: "Recap parsed",
        stamp: "System ready",
        status: "document-supported",
        detail: "Owner and charterer obligations extracted into tasks and deadlines.",
      },
      {
        title: "Arrival at Outer Roads",
        stamp: "Logged 12:30 LT",
        status: "next trigger",
        detail: "Arrival report upload unlocks NOR tender condition checks.",
      },
      {
        title: "NOR tender",
        stamp: "Awaiting event",
        status: "risk check",
        detail: "System flags laycan, place, and working-hours alignment without legal conclusion.",
      },
      {
        title: "Loading complete",
        stamp: "Expected today",
        status: "freight prep",
        detail: "Draft survey and mate's receipt will activate freight countdown after B/L signing.",
      },
      {
        title: "B/L signed",
        stamp: "Next trigger",
        status: "payment due",
        detail: "Charterer payment task opens with +3 banking days deadline.",
      },
    ],
    drafts: [
      {
        audience: "To Charterer",
        subject: "Freight due reminder",
        body: "Good day, kindly note freight will fall due within 3 banking days after signing of B/L as per recap terms. Please keep funds arranged accordingly.",
      },
      {
        audience: "To Master / Ops",
        subject: "NOR timing reminder",
        body: "Reminder: NOR must not be tendered prior to laycan. Please ensure timing and place of tender strictly follow recap terms.",
      },
      {
        audience: "To Owners",
        subject: "Holds failure draft",
        body: "Good day, pls note holds inspection has failed as per attached survey report. Owners are arranging immediate cleaning. Fresh NOR to be tendered once vessel is fully ready.",
      },
    ],
  },
  {
    id: "demo-02",
    vessel: "MV Linden Strait",
    owner: "Fjord Harvest Shipping",
    charterer: "Silver Harvest Commodities",
    broker: "Beacon Chartering",
    cargo: "6,100 MT soybean meal",
    route: "Eastport › Bayhaven",
    freight: "USD 231,800",
    paymentTerm: "2 banking days after signed B/L copy",
    status: "Discharging",
    stage: "DISCHARGING",
    nextTrigger: "Final DA review",
    nextDeadline: "Balance settlement due",
    riskLevel: "High",
    health: {
      label: "High risk",
      tone: "high",
      reasons: ["Agent nomination overdue", "Final DA support missing"],
    },
    parserSummary: [
      { label: "Freight term", value: "2 banking days after signed B/L copy" },
      { label: "DA clause", value: "Balance due within 3 banking days from invoice" },
    ],
    flags: [
      { title: "Agent nomination overdue", severity: "high" },
      { title: "Final DA not uploaded", severity: "medium" },
    ],
    summary: [
      ["Owner", "Fjord Harvest Shipping"],
      ["Charterer", "Silver Harvest Commodities"],
      ["Broker", "Beacon Chartering"],
      ["Cargo", "6,100 MT soybean meal"],
      ["Route", "Eastport › Bayhaven"],
      ["Status", "Discharging"],
      ["Next deadline", "Balance settlement due"],
      ["Risk", "High"],
    ],
    ownerTasks: [],
    chartererTasks: [],
    triggers: [],
    documents: [],
    riskNotes: [],
    timeline: [],
    drafts: [],
  },
];

export const demoVoyage = voyages[0];
