import type { VoyageRecord } from "./types";

export const voyages: VoyageRecord[] = [
  {
    id: "demo",
    vessel: "MV Cedar Bay",
    owner: "Northshore Bulk Pte. Ltd.",
    charterer: "Golden Delta Foods",
    broker: "Harborline Brokers",
    cargo: "4,800 MT corn",
    route: "Novorise › Southbay",
    freight: "USD 168,000",
    paymentTerm: "Within 3 banking days after B/L signing",
    status: "Loading",
    stage: "LOADING",
    upcomingTrigger: "B/L signing",
    nextDeadline: "ETA 5 days notice",
    commercialRisk: "Medium",
    health: {
      label: "At risk",
      tone: "at_risk",
      reasons: [
        "NOR timing requires review against laycan wording",
        "B/L copy has not yet been uploaded",
        "SOF remains missing from the evidence pack",
      ],
    },
    lastUpdatedAt: "14 Mar 2026, 14:20 LT",
    lastUpdatedBy: "Owner ops",
    lastEventRecorded: "Loading complete pending B/L signing confirmation",
    parserSummary: [
      { label: "Freight term", value: "3 banking days after B/L signing" },
      { label: "Payment trigger", value: "Signed B/L upload appears to start freight countdown" },
      { label: "Demurrage", value: "USD 6,000 PD" },
      { label: "Claim deadline", value: "15 business days after discharge" },
      { label: "Claim pack docs", value: "NOR, SOF, laytime sheet, supporting correspondence" },
      { label: "Owner critical clause", value: "NOR timing and hold readiness require review against recap wording" },
      { label: "Charterer critical clause", value: "PDA handling and freight funding appear to require action before B/L trigger" },
      { label: "Laytime exclusion", value: "Weather and non-ready holds period may not count, subject to clause review" },
    ],
    flags: [
      {
        title: "Freight deadline approaching",
        severity: "medium",
        guidance: "Upcoming B/L signing appears likely to activate the freight payment window.",
      },
      {
        title: "Missing SOF",
        severity: "high",
        guidance: "Supporting discharge and claim review may be delayed until SOF is uploaded.",
      },
      {
        title: "NOR before laycan risk",
        severity: "medium",
        guidance: "Review recommended against recap timing and tender-place wording.",
      },
    ],
    changesSinceLastUpdate: [
      {
        title: "New event logged",
        detail: "Arrival at outer roads recorded by owner ops.",
        stamp: "Today · 12:30 LT",
      },
      {
        title: "Document uploaded",
        detail: "Arrival report added to evidence pack.",
        stamp: "Today · 12:42 LT",
      },
      {
        title: "Risk increased",
        detail: "SOF remains missing while B/L signing is now the upcoming trigger.",
        stamp: "Today · 13:10 LT",
      },
    ],
    summary: [
      ["Owner", "Northshore Bulk Pte. Ltd."],
      ["Charterer", "Golden Delta Foods"],
      ["Broker", "Harborline Brokers"],
      ["Cargo", "4,800 MT corn"],
      ["Loadport", "Novorise"],
      ["Disport", "Southbay"],
      ["Freight", "4,800 × 35 = USD 168,000"],
      ["Payment", "3 banking days after B/L signing"],
    ],
    ownerTasks: [
      {
        title: "ETA 5 days notice",
        owner: "Owner",
        detail: "Reminder draft prepared for master and ops.",
        status: "pending",
        today: true,
        actions: [
          { label: "Send ETA Notice", tone: "primary" },
          { label: "Edit Reminder" },
        ],
        clauseSource: {
          title: "ETA notices clause",
          text: "5/4/3/2/1 day notices appear required before arrival.",
        },
        whyMatters: "Keeps counterparties aligned on approach timing and expected trigger sequence.",
        riskIfMissed: "Late notice may affect readiness coordination and increase dispute risk.",
      },
      {
        title: "NOR template ready",
        owner: "Owner",
        detail: "Template checked against laycan and tender location wording.",
        status: "ready",
        today: true,
        actions: [
          { label: "Upload NOR", tone: "primary" },
          { label: "Mark NOR Tendered" },
        ],
        clauseSource: {
          title: "NOR tender clause",
          text: "NOR timing and place appear tied to laycan and allowed tender location.",
        },
        whyMatters: "This is the likely trigger for laytime review and later claim support.",
        riskIfMissed: "Incorrect tender timing may require review and could reduce reliance on the notice.",
      },
      {
        title: "Holds inspection follow-up",
        owner: "Owner",
        detail: "Awaiting surveyor result and photo upload.",
        status: "active",
        actions: [
          { label: "Upload Hold Photos", tone: "primary" },
          { label: "Upload Survey Report" },
        ],
        clauseSource: {
          title: "Readiness clause",
          text: "Holds appear to need to be clean and ready before NOR can be relied upon.",
        },
        whyMatters: "Readiness evidence supports the operational record and any later timing review.",
        riskIfMissed: "Missing evidence may weaken the timeline and increase recap interpretation disputes.",
      },
      {
        title: "Demurrage claim pack window",
        owner: "Owner",
        detail: "15 business day filing clock appears to activate after discharge.",
        status: "pending",
        actions: [{ label: "Open Claim Builder", tone: "primary" }],
        clauseSource: {
          title: "Claim deadline clause",
          text: "Demurrage claim appears to require docs within 15 business days after discharge.",
        },
        whyMatters: "Prepares the support pack before the post-discharge deadline tightens.",
        riskIfMissed: "Late or incomplete filing may reduce claim defensibility and require manual review.",
      },
    ],
    chartererTasks: [
      {
        title: "Agent nomination",
        owner: "Charterer",
        detail: "Loadport agent nomination still missing.",
        status: "pending",
        today: true,
        actions: [
          { label: "Upload Nomination", tone: "primary" },
          { label: "Notify Agent" },
        ],
        clauseSource: {
          title: "Agent appointment clause",
          text: "Charterer side appears responsible for appointing the loadport agent.",
        },
        whyMatters: "Agent setup supports port coordination, paperwork flow, and cost handling.",
        riskIfMissed: "Delay may affect port readiness and later DA review.",
      },
      {
        title: "PDA entry",
        owner: "Charterer",
        detail: "Expected PDA deduction should be uploaded before freight due.",
        status: "pending",
        actions: [{ label: "Upload PDA", tone: "primary" }],
        clauseSource: {
          title: "PDA deduction clause",
          text: "PDA may be deducted from freight, subject to recap wording and support.",
        },
        whyMatters: "Clarifies the likely payable amount before the freight trigger activates.",
        riskIfMissed: "Freight reminder and balance review may use incomplete figures.",
      },
      {
        title: "Freight instruction prep",
        owner: "Charterer",
        detail: "Remittance path drafted, awaiting B/L signing trigger.",
        status: "ready",
        today: true,
        actions: [
          { label: "Generate Freight Reminder", tone: "primary" },
          { label: "Upload Payment Proof" },
        ],
        clauseSource: {
          title: "Freight payment clause",
          text: "Freight appears payable within 3 banking days after B/L signing.",
        },
        whyMatters: "Allows the team to move quickly once the B/L event is recorded.",
        riskIfMissed: "Funding delay may increase commercial pressure and escalate counterparty messaging.",
      },
      {
        title: "Surveyor nomination",
        owner: "Charterer",
        detail: "Cargo and hold survey contacts not yet confirmed.",
        status: "active",
        actions: [{ label: "Add Surveyor", tone: "primary" }],
        clauseSource: {
          title: "Survey coordination clause",
          text: "Survey and cargo documentation appear to require charterer-side coordination.",
        },
        whyMatters: "Provides the evidence base for cargo, readiness, and quantity review.",
        riskIfMissed: "Document gaps may delay operational closure and later adjustment review.",
      },
    ],
    triggers: [
      "Arrival at outer roads",
      "NOR tender",
      "Loading complete",
      "B/L signed",
      "Freight due",
      "Discharge complete",
      "Demurrage claim deadline",
    ],
    documents: [
      { title: "Recap / CP extract", status: "confirmed" },
      { title: "Arrival report", status: "uploaded" },
      { title: "NOR", status: "draft_only" },
      { title: "Survey report / hold photos", status: "awaiting_review" },
      { title: "B/L", status: "missing" },
      { title: "SOF", status: "missing" },
      { title: "PDA / Final DA invoice", status: "draft_only" },
      { title: "SWIFT payment proof", status: "missing" },
    ],
    riskNotes: [
      "NOR timing appears to require review against laycan and tender-place wording.",
      "Failed hold inspection may affect whether time counts during the failure period.",
      "Freight amount may be adjusted by PDA if the recap clause and support align.",
      "Claim timing appears to require signed SOF and laytime support before deadline review.",
    ],
    timeline: [
      {
        title: "Recap parsed",
        stamp: "Recorded event · System",
        status: "document-supported",
        detail: "Owner and charterer obligations were extracted into tasks and deadlines.",
      },
      {
        title: "Arrival at outer roads",
        stamp: "Recorded event · 12:30 LT",
        status: "next trigger",
        detail: "Arrival report upload now appears to activate NOR tender checks.",
      },
      {
        title: "NOR tender",
        stamp: "Upcoming trigger",
        status: "risk check",
        detail: "System indicates timing, place, and working-hours review is recommended before tender reliance.",
      },
      {
        title: "Loading complete",
        stamp: "Recorded event pending confirmation",
        status: "freight prep",
        detail: "Draft survey and mate's receipt appear to be the next support items before B/L signing.",
      },
      {
        title: "B/L signed",
        stamp: "Upcoming trigger",
        status: "payment due",
        detail: "Once recorded, this event appears likely to open the freight payment countdown.",
      },
    ],
    drafts: [
      {
        audience: "To Charterer",
        subject: "Freight due reminder",
        body: "Good day, kindly note freight will fall due within 3 banking days after signing of B/L as per recap terms. Please keep funds arranged accordingly.",
      },
      {
        audience: "To Master / Ops",
        subject: "NOR timing reminder",
        body: "Reminder: NOR must not be tendered prior to laycan. Please ensure timing and place of tender strictly follow recap terms.",
      },
      {
        audience: "To Owners",
        subject: "Holds failure draft",
        body: "Good day, pls note holds inspection has failed as per attached survey report. Owners are arranging immediate cleaning. Fresh NOR to be tendered once vessel is fully ready.",
      },
    ],
  },
  {
    id: "demo-02",
    vessel: "MV Linden Strait",
    owner: "Fjord Harvest Shipping",
    charterer: "Silver Harvest Commodities",
    broker: "Beacon Chartering",
    cargo: "6,100 MT soybean meal",
    route: "Eastport › Bayhaven",
    freight: "USD 231,800",
    paymentTerm: "2 banking days after signed B/L copy",
    status: "Discharging",
    stage: "DISCHARGING",
    upcomingTrigger: "Final DA review",
    nextDeadline: "Balance settlement due",
    commercialRisk: "High",
    health: {
      label: "Delayed",
      tone: "delayed",
      reasons: ["Agent nomination was late", "Final DA support remains incomplete"],
    },
    lastUpdatedAt: "14 Mar 2026, 11:05 LT",
    lastUpdatedBy: "Charterer ops",
    lastEventRecorded: "Discharge operations extended into review window",
    parserSummary: [
      { label: "Freight term", value: "2 banking days after signed B/L copy" },
      { label: "DA clause", value: "Balance due within 3 banking days from invoice" },
      { label: "Owner critical clause", value: "Final DA review appears to depend on supporting line items" },
      { label: "Charterer critical clause", value: "Invoice support remains required before balance tracking can settle" },
    ],
    flags: [
      {
        title: "Agent nomination overdue",
        severity: "high",
        guidance: "Delay may continue to affect coordination and review timing.",
      },
      {
        title: "Final DA not uploaded",
        severity: "medium",
        guidance: "Balance review appears incomplete until invoice support is added.",
      },
    ],
    changesSinceLastUpdate: [
      {
        title: "Deadline moved",
        detail: "Balance settlement now tracked from charterer invoice date.",
        stamp: "Yesterday · 18:20 LT",
      },
    ],
    summary: [
      ["Owner", "Fjord Harvest Shipping"],
      ["Charterer", "Silver Harvest Commodities"],
      ["Broker", "Beacon Chartering"],
      ["Cargo", "6,100 MT soybean meal"],
      ["Route", "Eastport › Bayhaven"],
      ["Status", "Discharging"],
      ["Next deadline", "Balance settlement due"],
      ["Commercial risk", "High"],
    ],
    ownerTasks: [],
    chartererTasks: [],
    triggers: [],
    documents: [
      { title: "Final DA invoice", status: "missing" },
      { title: "Supporting line items", status: "awaiting_review" },
    ],
    riskNotes: [],
    timeline: [],
    drafts: [],
  },
];

export const demoVoyage = voyages[0];
